// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql"
)

type Bot struct {
	ID                     string         `json:"id"`
	OwnerUserID            string         `json:"owner_user_id"`
	Type                   string         `json:"type"`
	DisplayName            sql.NullString `json:"display_name"`
	AvatarUrl              sql.NullString `json:"avatar_url"`
	Timezone               sql.NullString `json:"timezone"`
	IsActive               int64          `json:"is_active"`
	Status                 string         `json:"status"`
	AclDefaultEffect       string         `json:"acl_default_effect"`
	Language               string         `json:"language"`
	ReasoningEnabled       int64          `json:"reasoning_enabled"`
	ReasoningEffort        string         `json:"reasoning_effort"`
	ChatModelID            sql.NullString `json:"chat_model_id"`
	SearchProviderID       sql.NullString `json:"search_provider_id"`
	MemoryProviderID       sql.NullString `json:"memory_provider_id"`
	HeartbeatEnabled       int64          `json:"heartbeat_enabled"`
	HeartbeatInterval      int64          `json:"heartbeat_interval"`
	HeartbeatPrompt        string         `json:"heartbeat_prompt"`
	HeartbeatModelID       sql.NullString `json:"heartbeat_model_id"`
	CompactionEnabled      int64          `json:"compaction_enabled"`
	CompactionThreshold    int64          `json:"compaction_threshold"`
	CompactionRatio        int64          `json:"compaction_ratio"`
	CompactionModelID      sql.NullString `json:"compaction_model_id"`
	TitleModelID           sql.NullString `json:"title_model_id"`
	ImageModelID           sql.NullString `json:"image_model_id"`
	DiscussProbeModelID    sql.NullString `json:"discuss_probe_model_id"`
	TtsModelID             sql.NullString `json:"tts_model_id"`
	TranscriptionModelID   sql.NullString `json:"transcription_model_id"`
	PersistFullToolResults int64          `json:"persist_full_tool_results"`
	ShowToolCallsInIm      int64          `json:"show_tool_calls_in_im"`
	ToolApprovalConfig     string         `json:"tool_approval_config"`
	DisplayEnabled         int64          `json:"display_enabled"`
	OverlayProvider        string         `json:"overlay_provider"`
	OverlayEnabled         int64          `json:"overlay_enabled"`
	OverlayConfig          string         `json:"overlay_config"`
	Metadata               string         `json:"metadata"`
	CreatedAt              string         `json:"created_at"`
	UpdatedAt              string         `json:"updated_at"`
}

type BotAclRule struct {
	ID                     string         `json:"id"`
	BotID                  string         `json:"bot_id"`
	Enabled                int64          `json:"enabled"`
	Description            sql.NullString `json:"description"`
	Action                 string         `json:"action"`
	Effect                 string         `json:"effect"`
	ChannelIdentityID      sql.NullString `json:"channel_identity_id"`
	SubjectChannelType     sql.NullString `json:"subject_channel_type"`
	SourceChannel          sql.NullString `json:"source_channel"`
	SourceConversationType sql.NullString `json:"source_conversation_type"`
	SourceConversationID   sql.NullString `json:"source_conversation_id"`
	SourceThreadID         sql.NullString `json:"source_thread_id"`
	CreatedByUserID        sql.NullString `json:"created_by_user_id"`
	CreatedAt              string         `json:"created_at"`
	UpdatedAt              string         `json:"updated_at"`
}

type BotChannelConfig struct {
	ID               string         `json:"id"`
	BotID            string         `json:"bot_id"`
	ChannelType      string         `json:"channel_type"`
	Credentials      string         `json:"credentials"`
	ExternalIdentity sql.NullString `json:"external_identity"`
	SelfIdentity     string         `json:"self_identity"`
	Routing          string         `json:"routing"`
	Capabilities     string         `json:"capabilities"`
	Disabled         int64          `json:"disabled"`
	VerifiedAt       sql.NullString `json:"verified_at"`
	CreatedAt        string         `json:"created_at"`
	UpdatedAt        string         `json:"updated_at"`
}

type BotChannelRoute struct {
	ID                     string         `json:"id"`
	BotID                  string         `json:"bot_id"`
	ChannelType            string         `json:"channel_type"`
	ChannelConfigID        sql.NullString `json:"channel_config_id"`
	ExternalConversationID string         `json:"external_conversation_id"`
	ExternalThreadID       sql.NullString `json:"external_thread_id"`
	ConversationType       sql.NullString `json:"conversation_type"`
	DefaultReplyTarget     sql.NullString `json:"default_reply_target"`
	ActiveSessionID        sql.NullString `json:"active_session_id"`
	Metadata               string         `json:"metadata"`
	CreatedAt              string         `json:"created_at"`
	UpdatedAt              string         `json:"updated_at"`
}

type BotEmailBinding struct {
	ID              string `json:"id"`
	BotID           string `json:"bot_id"`
	EmailProviderID string `json:"email_provider_id"`
	EmailAddress    string `json:"email_address"`
	CanRead         int64  `json:"can_read"`
	CanWrite        int64  `json:"can_write"`
	CanDelete       int64  `json:"can_delete"`
	Config          string `json:"config"`
	CreatedAt       string `json:"created_at"`
	UpdatedAt       string `json:"updated_at"`
}

type BotHeartbeatLog struct {
	ID           string         `json:"id"`
	BotID        string         `json:"bot_id"`
	SessionID    sql.NullString `json:"session_id"`
	Status       string         `json:"status"`
	ResultText   string         `json:"result_text"`
	ErrorMessage string         `json:"error_message"`
	Usage        sql.NullString `json:"usage"`
	ModelID      sql.NullString `json:"model_id"`
	StartedAt    string         `json:"started_at"`
	CompletedAt  sql.NullString `json:"completed_at"`
}

type BotHistoryMessage struct {
	ID                      string         `json:"id"`
	BotID                   string         `json:"bot_id"`
	SessionID               sql.NullString `json:"session_id"`
	SenderChannelIdentityID sql.NullString `json:"sender_channel_identity_id"`
	SenderAccountUserID     sql.NullString `json:"sender_account_user_id"`
	SourceMessageID         sql.NullString `json:"source_message_id"`
	SourceReplyToMessageID  sql.NullString `json:"source_reply_to_message_id"`
	Role                    string         `json:"role"`
	Content                 string         `json:"content"`
	Metadata                string         `json:"metadata"`
	Usage                   sql.NullString `json:"usage"`
	ModelID                 sql.NullString `json:"model_id"`
	CompactID               sql.NullString `json:"compact_id"`
	EventID                 sql.NullString `json:"event_id"`
	DisplayText             sql.NullString `json:"display_text"`
	CreatedAt               string         `json:"created_at"`
}

type BotHistoryMessageAsset struct {
	ID          string `json:"id"`
	MessageID   string `json:"message_id"`
	Role        string `json:"role"`
	Ordinal     int64  `json:"ordinal"`
	ContentHash string `json:"content_hash"`
	Name        string `json:"name"`
	Metadata    string `json:"metadata"`
	CreatedAt   string `json:"created_at"`
}

type BotHistoryMessageCompact struct {
	ID           string         `json:"id"`
	BotID        string         `json:"bot_id"`
	SessionID    sql.NullString `json:"session_id"`
	Status       string         `json:"status"`
	Summary      string         `json:"summary"`
	MessageCount int64          `json:"message_count"`
	ErrorMessage string         `json:"error_message"`
	Usage        sql.NullString `json:"usage"`
	ModelID      sql.NullString `json:"model_id"`
	StartedAt    string         `json:"started_at"`
	CompletedAt  sql.NullString `json:"completed_at"`
}

type BotSession struct {
	ID              string         `json:"id"`
	BotID           string         `json:"bot_id"`
	RouteID         sql.NullString `json:"route_id"`
	ChannelType     sql.NullString `json:"channel_type"`
	Type            string         `json:"type"`
	Title           string         `json:"title"`
	Metadata        string         `json:"metadata"`
	ParentSessionID sql.NullString `json:"parent_session_id"`
	FinalizedAt     sql.NullString `json:"finalized_at"`
	CreatedAt       string         `json:"created_at"`
	UpdatedAt       string         `json:"updated_at"`
	DeletedAt       sql.NullString `json:"deleted_at"`
}

type BotSessionEvent struct {
	ID                      string         `json:"id"`
	BotID                   string         `json:"bot_id"`
	SessionID               string         `json:"session_id"`
	EventKind               string         `json:"event_kind"`
	EventData               string         `json:"event_data"`
	ExternalMessageID       sql.NullString `json:"external_message_id"`
	SenderChannelIdentityID sql.NullString `json:"sender_channel_identity_id"`
	ReceivedAtMs            int64          `json:"received_at_ms"`
	CreatedAt               string         `json:"created_at"`
}

type BotStorageBinding struct {
	ID                string `json:"id"`
	BotID             string `json:"bot_id"`
	StorageProviderID string `json:"storage_provider_id"`
	BasePath          string `json:"base_path"`
	CreatedAt         string `json:"created_at"`
	UpdatedAt         string `json:"updated_at"`
}

type ChannelIdentity struct {
	ID               string         `json:"id"`
	ChannelType      string         `json:"channel_type"`
	ChannelSubjectID string         `json:"channel_subject_id"`
	DisplayName      sql.NullString `json:"display_name"`
	AvatarUrl        sql.NullString `json:"avatar_url"`
	Metadata         string         `json:"metadata"`
	CreatedAt        string         `json:"created_at"`
	UpdatedAt        string         `json:"updated_at"`
}

type Container struct {
	ID               string         `json:"id"`
	BotID            string         `json:"bot_id"`
	ContainerID      string         `json:"container_id"`
	ContainerName    string         `json:"container_name"`
	Image            string         `json:"image"`
	Status           string         `json:"status"`
	Namespace        string         `json:"namespace"`
	AutoStart        int64          `json:"auto_start"`
	ContainerPath    string         `json:"container_path"`
	CreatedAt        string         `json:"created_at"`
	UpdatedAt        string         `json:"updated_at"`
	LastStartedAt    sql.NullString `json:"last_started_at"`
	LastStoppedAt    sql.NullString `json:"last_stopped_at"`
	WorkspaceBackend string         `json:"workspace_backend"`
}

type ContainerVersion struct {
	ID          string `json:"id"`
	ContainerID string `json:"container_id"`
	SnapshotID  string `json:"snapshot_id"`
	Version     int64  `json:"version"`
	CreatedAt   string `json:"created_at"`
}

type EmailOauthToken struct {
	ID              string         `json:"id"`
	EmailProviderID string         `json:"email_provider_id"`
	EmailAddress    string         `json:"email_address"`
	AccessToken     string         `json:"access_token"`
	RefreshToken    string         `json:"refresh_token"`
	ExpiresAt       sql.NullString `json:"expires_at"`
	Scope           string         `json:"scope"`
	State           string         `json:"state"`
	CreatedAt       string         `json:"created_at"`
	UpdatedAt       string         `json:"updated_at"`
}

type EmailOutbox struct {
	ID          string         `json:"id"`
	ProviderID  string         `json:"provider_id"`
	BotID       string         `json:"bot_id"`
	MessageID   string         `json:"message_id"`
	FromAddress string         `json:"from_address"`
	ToAddresses string         `json:"to_addresses"`
	Subject     string         `json:"subject"`
	BodyText    string         `json:"body_text"`
	BodyHtml    string         `json:"body_html"`
	Attachments string         `json:"attachments"`
	Status      string         `json:"status"`
	Error       string         `json:"error"`
	SentAt      sql.NullString `json:"sent_at"`
	CreatedAt   string         `json:"created_at"`
}

type EmailProvider struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	Provider  string `json:"provider"`
	Config    string `json:"config"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
}

type LifecycleEvent struct {
	ID          string `json:"id"`
	ContainerID string `json:"container_id"`
	EventType   string `json:"event_type"`
	Payload     string `json:"payload"`
	CreatedAt   string `json:"created_at"`
}

type McpConnection struct {
	ID            string         `json:"id"`
	BotID         string         `json:"bot_id"`
	Name          string         `json:"name"`
	Type          string         `json:"type"`
	Config        string         `json:"config"`
	IsActive      int64          `json:"is_active"`
	Status        string         `json:"status"`
	ToolsCache    string         `json:"tools_cache"`
	LastProbedAt  sql.NullString `json:"last_probed_at"`
	StatusMessage string         `json:"status_message"`
	AuthType      string         `json:"auth_type"`
	CreatedAt     string         `json:"created_at"`
	UpdatedAt     string         `json:"updated_at"`
}

type McpOauthToken struct {
	ID                     string         `json:"id"`
	ConnectionID           string         `json:"connection_id"`
	ResourceMetadataUrl    string         `json:"resource_metadata_url"`
	AuthorizationServerUrl string         `json:"authorization_server_url"`
	AuthorizationEndpoint  string         `json:"authorization_endpoint"`
	TokenEndpoint          string         `json:"token_endpoint"`
	RegistrationEndpoint   string         `json:"registration_endpoint"`
	ScopesSupported        string         `json:"scopes_supported"`
	ClientID               string         `json:"client_id"`
	ClientSecret           string         `json:"client_secret"`
	AccessToken            string         `json:"access_token"`
	RefreshToken           string         `json:"refresh_token"`
	TokenType              string         `json:"token_type"`
	ExpiresAt              sql.NullString `json:"expires_at"`
	Scope                  string         `json:"scope"`
	PkceCodeVerifier       string         `json:"pkce_code_verifier"`
	StateParam             string         `json:"state_param"`
	ResourceUri            string         `json:"resource_uri"`
	RedirectUri            string         `json:"redirect_uri"`
	CreatedAt              string         `json:"created_at"`
	UpdatedAt              string         `json:"updated_at"`
}

type MemoryProvider struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	Provider  string `json:"provider"`
	Config    string `json:"config"`
	IsDefault int64  `json:"is_default"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
}

type Model struct {
	ID         string         `json:"id"`
	ModelID    string         `json:"model_id"`
	Name       sql.NullString `json:"name"`
	ProviderID string         `json:"provider_id"`
	Type       string         `json:"type"`
	Config     string         `json:"config"`
	CreatedAt  string         `json:"created_at"`
	UpdatedAt  string         `json:"updated_at"`
}

type ModelVariant struct {
	ID        string `json:"id"`
	ModelUuid string `json:"model_uuid"`
	VariantID string `json:"variant_id"`
	Weight    int64  `json:"weight"`
	Metadata  string `json:"metadata"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
}

type OrchestrationArtifact struct {
	ID          string         `json:"id"`
	RunID       string         `json:"run_id"`
	TaskID      string         `json:"task_id"`
	AttemptID   sql.NullString `json:"attempt_id"`
	Kind        string         `json:"kind"`
	Uri         string         `json:"uri"`
	Version     string         `json:"version"`
	Digest      string         `json:"digest"`
	ContentType string         `json:"content_type"`
	Summary     string         `json:"summary"`
	Metadata    string         `json:"metadata"`
	CreatedAt   string         `json:"created_at"`
}

type OrchestrationEvent struct {
	ID               string         `json:"id"`
	RunID            string         `json:"run_id"`
	TaskID           sql.NullString `json:"task_id"`
	AttemptID        sql.NullString `json:"attempt_id"`
	CheckpointID     sql.NullString `json:"checkpoint_id"`
	Seq              int64          `json:"seq"`
	AggregateType    string         `json:"aggregate_type"`
	AggregateID      string         `json:"aggregate_id"`
	AggregateVersion int64          `json:"aggregate_version"`
	Type             string         `json:"type"`
	CausationEventID sql.NullString `json:"causation_event_id"`
	CorrelationID    string         `json:"correlation_id"`
	IdempotencyKey   string         `json:"idempotency_key"`
	Payload          string         `json:"payload"`
	CreatedAt        string         `json:"created_at"`
	PublishedAt      sql.NullString `json:"published_at"`
}

type OrchestrationHumanCheckpoint struct {
	ID                       string         `json:"id"`
	RunID                    string         `json:"run_id"`
	TaskID                   string         `json:"task_id"`
	BlocksRun                int64          `json:"blocks_run"`
	Kind                     string         `json:"kind"`
	ReasonCode               string         `json:"reason_code"`
	TriggeredBy              string         `json:"triggered_by"`
	Severity                 string         `json:"severity"`
	PlannerEpoch             int64          `json:"planner_epoch"`
	SupersededByPlannerEpoch sql.NullInt64  `json:"superseded_by_planner_epoch"`
	Status                   string         `json:"status"`
	StatusVersion            int64          `json:"status_version"`
	Question                 string         `json:"question"`
	Options                  string         `json:"options"`
	DefaultAction            string         `json:"default_action"`
	ResumePolicy             string         `json:"resume_policy"`
	TimeoutAt                sql.NullString `json:"timeout_at"`
	ResolvedBy               string         `json:"resolved_by"`
	ResolvedOption           string         `json:"resolved_option"`
	ResolvedResponse         string         `json:"resolved_response"`
	ResolvedAt               sql.NullString `json:"resolved_at"`
	Metadata                 string         `json:"metadata"`
	CreatedAt                string         `json:"created_at"`
	UpdatedAt                string         `json:"updated_at"`
}

type OrchestrationIdempotencyRecord struct {
	ID              string `json:"id"`
	TenantID        string `json:"tenant_id"`
	CallerSubject   string `json:"caller_subject"`
	Method          string `json:"method"`
	TargetID        string `json:"target_id"`
	IdempotencyKey  string `json:"idempotency_key"`
	RequestHash     string `json:"request_hash"`
	State           string `json:"state"`
	ResponsePayload string `json:"response_payload"`
	CreatedAt       string `json:"created_at"`
	UpdatedAt       string `json:"updated_at"`
}

type OrchestrationInputManifest struct {
	ID                          string `json:"id"`
	RunID                       string `json:"run_id"`
	TaskID                      string `json:"task_id"`
	CapturedTaskInputs          string `json:"captured_task_inputs"`
	CapturedArtifactVersions    string `json:"captured_artifact_versions"`
	CapturedBlackboardRevisions string `json:"captured_blackboard_revisions"`
	ProjectionHash              string `json:"projection_hash"`
	CreatedAt                   string `json:"created_at"`
}

type OrchestrationPlanningIntent struct {
	ID               string         `json:"id"`
	RunID            string         `json:"run_id"`
	TaskID           sql.NullString `json:"task_id"`
	CheckpointID     sql.NullString `json:"checkpoint_id"`
	Kind             string         `json:"kind"`
	Status           string         `json:"status"`
	BasePlannerEpoch int64          `json:"base_planner_epoch"`
	ClaimEpoch       int64          `json:"claim_epoch"`
	ClaimToken       string         `json:"claim_token"`
	ClaimedBy        string         `json:"claimed_by"`
	LeaseExpiresAt   sql.NullString `json:"lease_expires_at"`
	LastHeartbeatAt  sql.NullString `json:"last_heartbeat_at"`
	FailureReason    string         `json:"failure_reason"`
	Payload          string         `json:"payload"`
	CreatedAt        string         `json:"created_at"`
	UpdatedAt        string         `json:"updated_at"`
}

type OrchestrationProjectionSnapshot struct {
	ID             string `json:"id"`
	RunID          string `json:"run_id"`
	ProjectionKind string `json:"projection_kind"`
	Seq            int64  `json:"seq"`
	Payload        string `json:"payload"`
	CreatedAt      string `json:"created_at"`
}

type OrchestrationRun struct {
	ID                     string         `json:"id"`
	TenantID               string         `json:"tenant_id"`
	OwnerSubject           string         `json:"owner_subject"`
	LifecycleStatus        string         `json:"lifecycle_status"`
	PlanningStatus         string         `json:"planning_status"`
	StatusVersion          int64          `json:"status_version"`
	PlannerEpoch           int64          `json:"planner_epoch"`
	LastEventSeq           int64          `json:"last_event_seq"`
	RootTaskID             string         `json:"root_task_id"`
	Goal                   string         `json:"goal"`
	Input                  string         `json:"input"`
	RequestedControlPolicy string         `json:"requested_control_policy"`
	ControlPolicy          string         `json:"control_policy"`
	SourceMetadata         string         `json:"source_metadata"`
	Policies               string         `json:"policies"`
	CreatedBy              string         `json:"created_by"`
	TerminalReason         string         `json:"terminal_reason"`
	CreatedAt              string         `json:"created_at"`
	UpdatedAt              string         `json:"updated_at"`
	FinishedAt             sql.NullString `json:"finished_at"`
}

type OrchestrationTask struct {
	ID                       string         `json:"id"`
	RunID                    string         `json:"run_id"`
	DecomposedFromTaskID     sql.NullString `json:"decomposed_from_task_id"`
	Kind                     string         `json:"kind"`
	Role                     string         `json:"role"`
	Goal                     string         `json:"goal"`
	Inputs                   string         `json:"inputs"`
	PlannerEpoch             int64          `json:"planner_epoch"`
	SupersededByPlannerEpoch sql.NullInt64  `json:"superseded_by_planner_epoch"`
	WorkerProfile            string         `json:"worker_profile"`
	Priority                 int64          `json:"priority"`
	RetryPolicy              string         `json:"retry_policy"`
	VerificationPolicy       string         `json:"verification_policy"`
	Status                   string         `json:"status"`
	StatusVersion            int64          `json:"status_version"`
	WaitingCheckpointID      sql.NullString `json:"waiting_checkpoint_id"`
	WaitingScope             string         `json:"waiting_scope"`
	LatestResultID           sql.NullString `json:"latest_result_id"`
	ReadyAt                  sql.NullString `json:"ready_at"`
	BlockedReason            string         `json:"blocked_reason"`
	TerminalReason           string         `json:"terminal_reason"`
	BlackboardScope          string         `json:"blackboard_scope"`
	CreatedAt                string         `json:"created_at"`
	UpdatedAt                string         `json:"updated_at"`
}

type OrchestrationTaskAttempt struct {
	ID               string         `json:"id"`
	RunID            string         `json:"run_id"`
	TaskID           string         `json:"task_id"`
	AttemptNo        int64          `json:"attempt_no"`
	WorkerID         string         `json:"worker_id"`
	ExecutorID       string         `json:"executor_id"`
	WorkerLeaseToken string         `json:"worker_lease_token"`
	Status           string         `json:"status"`
	ClaimEpoch       int64          `json:"claim_epoch"`
	ClaimToken       string         `json:"claim_token"`
	LeaseExpiresAt   sql.NullString `json:"lease_expires_at"`
	LastHeartbeatAt  sql.NullString `json:"last_heartbeat_at"`
	InputManifestID  sql.NullString `json:"input_manifest_id"`
	ParkCheckpointID sql.NullString `json:"park_checkpoint_id"`
	SessionID        sql.NullString `json:"session_id"`
	FailureClass     string         `json:"failure_class"`
	TerminalReason   string         `json:"terminal_reason"`
	StartedAt        sql.NullString `json:"started_at"`
	FinishedAt       sql.NullString `json:"finished_at"`
	CreatedAt        string         `json:"created_at"`
	UpdatedAt        string         `json:"updated_at"`
}

type OrchestrationTaskDependency struct {
	ID                       string        `json:"id"`
	RunID                    string        `json:"run_id"`
	PredecessorTaskID        string        `json:"predecessor_task_id"`
	SuccessorTaskID          string        `json:"successor_task_id"`
	PlannerEpoch             int64         `json:"planner_epoch"`
	SupersededByPlannerEpoch sql.NullInt64 `json:"superseded_by_planner_epoch"`
	CreatedAt                string        `json:"created_at"`
	UpdatedAt                string        `json:"updated_at"`
}

type OrchestrationTaskResult struct {
	ID               string         `json:"id"`
	RunID            string         `json:"run_id"`
	TaskID           string         `json:"task_id"`
	AttemptID        sql.NullString `json:"attempt_id"`
	Status           string         `json:"status"`
	Summary          string         `json:"summary"`
	FailureClass     string         `json:"failure_class"`
	RequestReplan    int64          `json:"request_replan"`
	ArtifactIntents  string         `json:"artifact_intents"`
	StructuredOutput string         `json:"structured_output"`
	CreatedAt        string         `json:"created_at"`
	UpdatedAt        string         `json:"updated_at"`
}

type OrchestrationTaskVerification struct {
	ID               string         `json:"id"`
	RunID            string         `json:"run_id"`
	TaskID           string         `json:"task_id"`
	ResultID         string         `json:"result_id"`
	AttemptNo        int64          `json:"attempt_no"`
	WorkerID         string         `json:"worker_id"`
	ExecutorID       string         `json:"executor_id"`
	WorkerLeaseToken string         `json:"worker_lease_token"`
	VerifierProfile  string         `json:"verifier_profile"`
	Status           string         `json:"status"`
	ClaimEpoch       int64          `json:"claim_epoch"`
	ClaimToken       string         `json:"claim_token"`
	LeaseExpiresAt   sql.NullString `json:"lease_expires_at"`
	LastHeartbeatAt  sql.NullString `json:"last_heartbeat_at"`
	SessionID        sql.NullString `json:"session_id"`
	Verdict          string         `json:"verdict"`
	Summary          string         `json:"summary"`
	FailureClass     string         `json:"failure_class"`
	TerminalReason   string         `json:"terminal_reason"`
	StartedAt        sql.NullString `json:"started_at"`
	FinishedAt       sql.NullString `json:"finished_at"`
	CreatedAt        string         `json:"created_at"`
	UpdatedAt        string         `json:"updated_at"`
}

type OrchestrationWorker struct {
	ID              string `json:"id"`
	ExecutorID      string `json:"executor_id"`
	DisplayName     string `json:"display_name"`
	Capabilities    string `json:"capabilities"`
	Status          string `json:"status"`
	LeaseToken      string `json:"lease_token"`
	LastHeartbeatAt string `json:"last_heartbeat_at"`
	LeaseExpiresAt  string `json:"lease_expires_at"`
	CreatedAt       string `json:"created_at"`
	UpdatedAt       string `json:"updated_at"`
}

type Provider struct {
	ID         string         `json:"id"`
	Name       string         `json:"name"`
	ClientType string         `json:"client_type"`
	Icon       sql.NullString `json:"icon"`
	Enable     int64          `json:"enable"`
	Config     string         `json:"config"`
	Metadata   string         `json:"metadata"`
	CreatedAt  string         `json:"created_at"`
	UpdatedAt  string         `json:"updated_at"`
}

type ProviderOauthToken struct {
	ID               string         `json:"id"`
	ProviderID       string         `json:"provider_id"`
	AccessToken      string         `json:"access_token"`
	RefreshToken     string         `json:"refresh_token"`
	ExpiresAt        sql.NullString `json:"expires_at"`
	Scope            string         `json:"scope"`
	TokenType        string         `json:"token_type"`
	State            string         `json:"state"`
	PkceCodeVerifier string         `json:"pkce_code_verifier"`
	CreatedAt        string         `json:"created_at"`
	UpdatedAt        string         `json:"updated_at"`
}

type Schedule struct {
	ID           string        `json:"id"`
	Name         string        `json:"name"`
	Description  string        `json:"description"`
	Pattern      string        `json:"pattern"`
	MaxCalls     sql.NullInt64 `json:"max_calls"`
	CurrentCalls int64         `json:"current_calls"`
	CreatedAt    string        `json:"created_at"`
	UpdatedAt    string        `json:"updated_at"`
	Enabled      int64         `json:"enabled"`
	Command      string        `json:"command"`
	BotID        string        `json:"bot_id"`
}

type ScheduleLog struct {
	ID           string         `json:"id"`
	ScheduleID   string         `json:"schedule_id"`
	BotID        string         `json:"bot_id"`
	SessionID    sql.NullString `json:"session_id"`
	Status       string         `json:"status"`
	ResultText   string         `json:"result_text"`
	ErrorMessage string         `json:"error_message"`
	Usage        sql.NullString `json:"usage"`
	ModelID      sql.NullString `json:"model_id"`
	StartedAt    string         `json:"started_at"`
	CompletedAt  sql.NullString `json:"completed_at"`
}

type SearchProvider struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	Provider  string `json:"provider"`
	Config    string `json:"config"`
	Enable    int64  `json:"enable"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
}

type Snapshot struct {
	ID                        string         `json:"id"`
	ContainerID               string         `json:"container_id"`
	RuntimeSnapshotName       string         `json:"runtime_snapshot_name"`
	DisplayName               sql.NullString `json:"display_name"`
	ParentRuntimeSnapshotName sql.NullString `json:"parent_runtime_snapshot_name"`
	Snapshotter               string         `json:"snapshotter"`
	Source                    string         `json:"source"`
	CreatedAt                 string         `json:"created_at"`
}

type StorageProvider struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	Provider  string `json:"provider"`
	Config    string `json:"config"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
}

type ToolApprovalRequest struct {
	ID                           string         `json:"id"`
	BotID                        string         `json:"bot_id"`
	SessionID                    string         `json:"session_id"`
	RouteID                      sql.NullString `json:"route_id"`
	ChannelIdentityID            sql.NullString `json:"channel_identity_id"`
	ToolCallID                   string         `json:"tool_call_id"`
	ToolName                     string         `json:"tool_name"`
	ToolInput                    string         `json:"tool_input"`
	ShortID                      int64          `json:"short_id"`
	Status                       string         `json:"status"`
	DecisionReason               string         `json:"decision_reason"`
	RequestedByChannelIdentityID sql.NullString `json:"requested_by_channel_identity_id"`
	DecidedByChannelIdentityID   sql.NullString `json:"decided_by_channel_identity_id"`
	RequestedMessageID           sql.NullString `json:"requested_message_id"`
	PromptMessageID              sql.NullString `json:"prompt_message_id"`
	PromptExternalMessageID      string         `json:"prompt_external_message_id"`
	SourcePlatform               string         `json:"source_platform"`
	ReplyTarget                  string         `json:"reply_target"`
	ConversationType             string         `json:"conversation_type"`
	CreatedAt                    string         `json:"created_at"`
	DecidedAt                    sql.NullString `json:"decided_at"`
}

type User struct {
	ID           string         `json:"id"`
	Username     sql.NullString `json:"username"`
	Email        sql.NullString `json:"email"`
	PasswordHash sql.NullString `json:"password_hash"`
	Role         string         `json:"role"`
	DisplayName  sql.NullString `json:"display_name"`
	AvatarUrl    sql.NullString `json:"avatar_url"`
	Timezone     string         `json:"timezone"`
	DataRoot     sql.NullString `json:"data_root"`
	LastLoginAt  sql.NullString `json:"last_login_at"`
	IsActive     int64          `json:"is_active"`
	Metadata     string         `json:"metadata"`
	CreatedAt    string         `json:"created_at"`
	UpdatedAt    string         `json:"updated_at"`
}

type UserChannelBinding struct {
	ID          string `json:"id"`
	UserID      string `json:"user_id"`
	ChannelType string `json:"channel_type"`
	Config      string `json:"config"`
	CreatedAt   string `json:"created_at"`
	UpdatedAt   string `json:"updated_at"`
}

type UserProviderOauthToken struct {
	ID               string         `json:"id"`
	ProviderID       string         `json:"provider_id"`
	UserID           string         `json:"user_id"`
	AccessToken      string         `json:"access_token"`
	RefreshToken     string         `json:"refresh_token"`
	ExpiresAt        sql.NullString `json:"expires_at"`
	Scope            string         `json:"scope"`
	TokenType        string         `json:"token_type"`
	State            string         `json:"state"`
	PkceCodeVerifier string         `json:"pkce_code_verifier"`
	Metadata         string         `json:"metadata"`
	CreatedAt        string         `json:"created_at"`
	UpdatedAt        string         `json:"updated_at"`
}
