// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: bot_setups.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimBotSetups = `-- name: ClaimBotSetups :many
UPDATE bot_setups
SET
  lease_owner = $1,
  lease_until = now() + make_interval(secs => $2::double precision),
  version     = version + 1,
  updated_at  = now()
WHERE bot_id IN (
  SELECT bot_id FROM bot_setups
  WHERE team_id = public.memoh_current_team_id()
    AND next_attempt_at <= now()
    AND (lease_until IS NULL OR lease_until < now())
    AND state <> 'done'
  ORDER BY next_attempt_at
  LIMIT $3::int
  FOR UPDATE SKIP LOCKED
)
RETURNING bot_id, team_id, desired_generation, spec, requested_by_user_id, state, observed_generation, attempts, next_attempt_at, lease_owner, lease_until, version, created_at, updated_at
`

type ClaimBotSetupsParams struct {
	LeaseOwner   string  `json:"lease_owner"`
	LeaseSeconds float64 `json:"lease_seconds"`
	Lim          int32   `json:"lim"`
}

// Claim due rows for one reconcile pass: not done, backoff elapsed, lease free
// or expired. Recording an intent resets state to 'pending', so state alone
// says whether the latest intent has been answered. SKIP LOCKED keeps
// concurrent Server instances from claiming the same row.
func (q *Queries) ClaimBotSetups(ctx context.Context, arg ClaimBotSetupsParams) ([]BotSetup, error) {
	rows, err := q.db.Query(ctx, claimBotSetups, arg.LeaseOwner, arg.LeaseSeconds, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BotSetup
	for rows.Next() {
		var i BotSetup
		if err := rows.Scan(
			&i.BotID,
			&i.TeamID,
			&i.DesiredGeneration,
			&i.Spec,
			&i.RequestedByUserID,
			&i.State,
			&i.ObservedGeneration,
			&i.Attempts,
			&i.NextAttemptAt,
			&i.LeaseOwner,
			&i.LeaseUntil,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBotSetup = `-- name: GetBotSetup :one
SELECT bot_id, team_id, desired_generation, spec, requested_by_user_id, state, observed_generation, attempts, next_attempt_at, lease_owner, lease_until, version, created_at, updated_at FROM bot_setups
WHERE team_id = public.memoh_current_team_id() AND bot_id = $1
`

func (q *Queries) GetBotSetup(ctx context.Context, botID pgtype.UUID) (BotSetup, error) {
	row := q.db.QueryRow(ctx, getBotSetup, botID)
	var i BotSetup
	err := row.Scan(
		&i.BotID,
		&i.TeamID,
		&i.DesiredGeneration,
		&i.Spec,
		&i.RequestedByUserID,
		&i.State,
		&i.ObservedGeneration,
		&i.Attempts,
		&i.NextAttemptAt,
		&i.LeaseOwner,
		&i.LeaseUntil,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listBotSetupSteps = `-- name: ListBotSetupSteps :many
SELECT bot_id, team_id, step, status, generation, attempts, last_error, updated_at FROM bot_setup_steps
WHERE team_id = public.memoh_current_team_id() AND bot_id = $1
ORDER BY step
`

func (q *Queries) ListBotSetupSteps(ctx context.Context, botID pgtype.UUID) ([]BotSetupStep, error) {
	rows, err := q.db.Query(ctx, listBotSetupSteps, botID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BotSetupStep
	for rows.Next() {
		var i BotSetupStep
		if err := rows.Scan(
			&i.BotID,
			&i.TeamID,
			&i.Step,
			&i.Status,
			&i.Generation,
			&i.Attempts,
			&i.LastError,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const releaseBotSetupLease = `-- name: ReleaseBotSetupLease :execrows
UPDATE bot_setups
SET
  lease_owner = '',
  lease_until = NULL,
  updated_at  = now()
WHERE team_id = public.memoh_current_team_id()
  AND bot_id = $1
  AND lease_owner = $2
`

type ReleaseBotSetupLeaseParams struct {
	BotID      pgtype.UUID `json:"bot_id"`
	LeaseOwner string      `json:"lease_owner"`
}

func (q *Queries) ReleaseBotSetupLease(ctx context.Context, arg ReleaseBotSetupLeaseParams) (int64, error) {
	result, err := q.db.Exec(ctx, releaseBotSetupLease, arg.BotID, arg.LeaseOwner)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const renewBotSetupLease = `-- name: RenewBotSetupLease :execrows
UPDATE bot_setups
SET
  lease_until = now() + make_interval(secs => $1::double precision),
  updated_at  = now()
WHERE team_id = public.memoh_current_team_id()
  AND bot_id = $2
  AND lease_owner = $3
`

type RenewBotSetupLeaseParams struct {
	LeaseSeconds float64     `json:"lease_seconds"`
	BotID        pgtype.UUID `json:"bot_id"`
	LeaseOwner   string      `json:"lease_owner"`
}

func (q *Queries) RenewBotSetupLease(ctx context.Context, arg RenewBotSetupLeaseParams) (int64, error) {
	result, err := q.db.Exec(ctx, renewBotSetupLease, arg.LeaseSeconds, arg.BotID, arg.LeaseOwner)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const resetBotSetupStepsNotDone = `-- name: ResetBotSetupStepsNotDone :exec
UPDATE bot_setup_steps
SET status = 'pending', attempts = 0, last_error = '', updated_at = now()
WHERE team_id = public.memoh_current_team_id()
  AND bot_id = $1
  AND status IN ('pending', 'running', 'retrying', 'failed')
`

// A retry re-runs every managed step that has not completed; done steps keep
// their result and skipped steps stay skipped.
func (q *Queries) ResetBotSetupStepsNotDone(ctx context.Context, botID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, resetBotSetupStepsNotDone, botID)
	return err
}

const retryBotSetupIntent = `-- name: RetryBotSetupIntent :one
UPDATE bot_setups
SET
  desired_generation = desired_generation + 1,
  state              = 'pending',
  attempts           = 0,
  next_attempt_at    = now(),
  version            = version + 1,
  updated_at         = now()
WHERE team_id = public.memoh_current_team_id() AND bot_id = $1
RETURNING bot_id, team_id, desired_generation, spec, requested_by_user_id, state, observed_generation, attempts, next_attempt_at, lease_owner, lease_until, version, created_at, updated_at
`

// Ask for another pass over the same spec: bump the generation and reset the
// retry budget. Steps already done stay done (see ResetBotSetupStepsNotDone).
func (q *Queries) RetryBotSetupIntent(ctx context.Context, botID pgtype.UUID) (BotSetup, error) {
	row := q.db.QueryRow(ctx, retryBotSetupIntent, botID)
	var i BotSetup
	err := row.Scan(
		&i.BotID,
		&i.TeamID,
		&i.DesiredGeneration,
		&i.Spec,
		&i.RequestedByUserID,
		&i.State,
		&i.ObservedGeneration,
		&i.Attempts,
		&i.NextAttemptAt,
		&i.LeaseOwner,
		&i.LeaseUntil,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateBotSetupObserved = `-- name: UpdateBotSetupObserved :one
UPDATE bot_setups
SET
  state               = $1,
  observed_generation = $2,
  attempts            = $3,
  next_attempt_at     = $4,
  lease_owner         = CASE WHEN $5::boolean THEN '' ELSE lease_owner END,
  lease_until         = CASE WHEN $5::boolean THEN NULL ELSE lease_until END,
  version             = version + 1,
  updated_at          = now()
WHERE team_id = public.memoh_current_team_id()
  AND bot_id = $6
  AND lease_owner = $7
  AND version = $8
RETURNING bot_id, team_id, desired_generation, spec, requested_by_user_id, state, observed_generation, attempts, next_attempt_at, lease_owner, lease_until, version, created_at, updated_at
`

type UpdateBotSetupObservedParams struct {
	State              string             `json:"state"`
	ObservedGeneration int64              `json:"observed_generation"`
	Attempts           int32              `json:"attempts"`
	NextAttemptAt      pgtype.Timestamptz `json:"next_attempt_at"`
	ReleaseLease       bool               `json:"release_lease"`
	BotID              pgtype.UUID        `json:"bot_id"`
	LeaseOwner         string             `json:"lease_owner"`
	ExpectedVersion    int64              `json:"expected_version"`
}

// Write an observation. The lease must still be held by the caller; the
// version pins the row the caller read so a concurrent intent bump is not
// silently overwritten.
func (q *Queries) UpdateBotSetupObserved(ctx context.Context, arg UpdateBotSetupObservedParams) (BotSetup, error) {
	row := q.db.QueryRow(ctx, updateBotSetupObserved,
		arg.State,
		arg.ObservedGeneration,
		arg.Attempts,
		arg.NextAttemptAt,
		arg.ReleaseLease,
		arg.BotID,
		arg.LeaseOwner,
		arg.ExpectedVersion,
	)
	var i BotSetup
	err := row.Scan(
		&i.BotID,
		&i.TeamID,
		&i.DesiredGeneration,
		&i.Spec,
		&i.RequestedByUserID,
		&i.State,
		&i.ObservedGeneration,
		&i.Attempts,
		&i.NextAttemptAt,
		&i.LeaseOwner,
		&i.LeaseUntil,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertBotSetupIntent = `-- name: UpsertBotSetupIntent :one

INSERT INTO bot_setups (bot_id, spec, requested_by_user_id)
VALUES ($1, $2, $3)
ON CONFLICT (bot_id) DO UPDATE SET
  desired_generation   = bot_setups.desired_generation + 1,
  spec                 = EXCLUDED.spec,
  requested_by_user_id = COALESCE(EXCLUDED.requested_by_user_id, bot_setups.requested_by_user_id),
  state                = 'pending',
  attempts             = 0,
  next_attempt_at      = now(),
  version              = bot_setups.version + 1,
  updated_at           = now()
RETURNING bot_id, team_id, desired_generation, spec, requested_by_user_id, state, observed_generation, attempts, next_attempt_at, lease_owner, lease_until, version, created_at, updated_at
`

type UpsertBotSetupIntentParams struct {
	BotID             pgtype.UUID `json:"bot_id"`
	Spec              []byte      `json:"spec"`
	RequestedByUserID pgtype.UUID `json:"requested_by_user_id"`
}

// Declarative post-create setup. Intent columns are written by the API layer;
// observation columns and the lease are written by the reconciler only.
// Record a new setup intent. A new row starts at generation 1; an existing
// row bumps the generation, replaces the spec, resets the retry budget and
// makes the row due now.
func (q *Queries) UpsertBotSetupIntent(ctx context.Context, arg UpsertBotSetupIntentParams) (BotSetup, error) {
	row := q.db.QueryRow(ctx, upsertBotSetupIntent, arg.BotID, arg.Spec, arg.RequestedByUserID)
	var i BotSetup
	err := row.Scan(
		&i.BotID,
		&i.TeamID,
		&i.DesiredGeneration,
		&i.Spec,
		&i.RequestedByUserID,
		&i.State,
		&i.ObservedGeneration,
		&i.Attempts,
		&i.NextAttemptAt,
		&i.LeaseOwner,
		&i.LeaseUntil,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertBotSetupStep = `-- name: UpsertBotSetupStep :one
INSERT INTO bot_setup_steps (bot_id, step, status, generation, attempts, last_error)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (bot_id, step) DO UPDATE SET
  status     = EXCLUDED.status,
  generation = EXCLUDED.generation,
  attempts   = EXCLUDED.attempts,
  last_error = EXCLUDED.last_error,
  updated_at = now()
RETURNING bot_id, team_id, step, status, generation, attempts, last_error, updated_at
`

type UpsertBotSetupStepParams struct {
	BotID      pgtype.UUID `json:"bot_id"`
	Step       string      `json:"step"`
	Status     string      `json:"status"`
	Generation int64       `json:"generation"`
	Attempts   int32       `json:"attempts"`
	LastError  string      `json:"last_error"`
}

func (q *Queries) UpsertBotSetupStep(ctx context.Context, arg UpsertBotSetupStepParams) (BotSetupStep, error) {
	row := q.db.QueryRow(ctx, upsertBotSetupStep,
		arg.BotID,
		arg.Step,
		arg.Status,
		arg.Generation,
		arg.Attempts,
		arg.LastError,
	)
	var i BotSetupStep
	err := row.Scan(
		&i.BotID,
		&i.TeamID,
		&i.Step,
		&i.Status,
		&i.Generation,
		&i.Attempts,
		&i.LastError,
		&i.UpdatedAt,
	)
	return i, err
}
